# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'RGUIKitDemo' do
#    inhibit_all_warnings!
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    #  pod 'XJIoTSDK', :git => 'git@gitee.com:app-develop/XJIoTSDK-ios.git'
    # pod 'XJIoTSDK', :path => '../XJIoTSDK-ios'
    # pod 'XJIoTUtil', :path => '../XJIoTUtil-ios'
    pod 'RGUIKit', :path => '../../RGUIKit'
    
#    post_install do |installer|
#        installer.pods_project.targets.each do |target|
#            target.build_configurations.each do |config|
#                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
#            end
#        end
#    end
end
